create table if not exists public.game_definitions (
  id text primary key,
  category text not null check (category in ('ten-seconds', 'one-minute', 'full-match')),
  name text not null,
  is_active boolean not null default true
);

create table if not exists public.game_reward_rules (
  id bigint generated by default as identity primary key,
  ticket_type text not null check (ticket_type in ('normal', 'premium')),
  min_score integer not null check (min_score between 0 and 100),
  requires_success boolean not null default true,
  priority integer not null default 0,
  is_active boolean not null default true,
  unique (ticket_type)
);

create table if not exists public.game_plays (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  game_id text not null references public.game_definitions(id),
  score integer check (score between 0 and 100),
  success boolean,
  play_time_seconds integer check (play_time_seconds >= 0),
  started_at timestamptz not null default now(),
  played_at timestamptz,
  status text not null default 'in_progress' check (status in ('in_progress', 'completed'))
);

create table if not exists public.game_rewards (
  id uuid primary key default gen_random_uuid(),
  game_play_id uuid not null unique references public.game_plays(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  ticket_type text not null check (ticket_type in ('normal', 'premium')),
  quantity integer not null default 1 check (quantity = 1),
  awarded_at timestamptz not null default now()
);

create index if not exists game_plays_user_played_idx on public.game_plays(user_id, played_at desc);
create index if not exists game_rewards_user_awarded_idx on public.game_rewards(user_id, awarded_at desc);

insert into public.game_definitions (id, category, name) values
  ('quick-rock-paper-scissors', 'ten-seconds', '초고속 가위바위보'),
  ('count-together', 'ten-seconds', '눈치 숫자 외치기'),
  ('speed-math', 'one-minute', '사칙연산 스피드'),
  ('word-chain', 'one-minute', '단어 이어 말하기'),
  ('couple-balance', 'full-match', '커플 밸런스 대결'),
  ('memory-cards', 'full-match', '기억력 카드 대결')
on conflict (id) do update set category = excluded.category, name = excluded.name;

-- 테스트 기준. 운영 전에는 이 데이터만 바꾸면 보상 기준을 조정할 수 있습니다.
insert into public.game_reward_rules (ticket_type, min_score, requires_success, priority) values
  ('normal', 60, true, 10),
  ('premium', 90, true, 20)
on conflict (ticket_type) do update set
  min_score = excluded.min_score,
  requires_success = excluded.requires_success,
  priority = excluded.priority;

alter table public.game_definitions enable row level security;
alter table public.game_reward_rules enable row level security;
alter table public.game_plays enable row level security;
alter table public.game_rewards enable row level security;

drop policy if exists game_definitions_select_authenticated on public.game_definitions;
create policy game_definitions_select_authenticated on public.game_definitions
  for select to authenticated using (is_active);

drop policy if exists game_reward_rules_select_authenticated on public.game_reward_rules;
create policy game_reward_rules_select_authenticated on public.game_reward_rules
  for select to authenticated using (is_active);

drop policy if exists game_plays_select_own on public.game_plays;
create policy game_plays_select_own on public.game_plays
  for select to authenticated using (user_id = auth.uid());

drop policy if exists game_rewards_select_own on public.game_rewards;
create policy game_rewards_select_own on public.game_rewards
  for select to authenticated using (user_id = auth.uid());

create or replace function public.start_game(input_game_id text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  new_play_id uuid;
begin
  if current_user_id is null then raise exception '로그인이 필요합니다.'; end if;
  if not exists (select 1 from public.game_definitions where id = input_game_id and is_active) then
    raise exception '플레이할 수 없는 게임입니다.';
  end if;
  insert into public.game_plays (user_id, game_id)
  values (current_user_id, input_game_id)
  returning id into new_play_id;
  return new_play_id;
end;
$$;

create or replace function public.finish_game(
  input_play_id uuid,
  input_score integer,
  input_success boolean
)
returns table (
  play_id uuid,
  rewarded_ticket_type text,
  rewarded_quantity integer,
  normal_balance integer,
  premium_balance integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_play public.game_plays%rowtype;
  selected_ticket_type text;
  elapsed_seconds integer;
begin
  if auth.uid() is null then raise exception '로그인이 필요합니다.'; end if;
  if input_score not between 0 and 100 then raise exception '점수는 0부터 100까지 입력할 수 있습니다.'; end if;

  select * into target_play from public.game_plays where id = input_play_id for update;
  if target_play.id is null then raise exception '게임 기록을 찾을 수 없습니다.'; end if;
  if target_play.user_id <> auth.uid() then raise exception '본인의 게임만 완료할 수 있습니다.'; end if;

  if target_play.status = 'in_progress' then
    elapsed_seconds := greatest(0, floor(extract(epoch from (now() - target_play.started_at)))::integer);
    update public.game_plays set
      score = input_score,
      success = input_success,
      play_time_seconds = elapsed_seconds,
      played_at = now(),
      status = 'completed'
    where id = input_play_id;

    select rule.ticket_type into selected_ticket_type
    from public.game_reward_rules rule
    where rule.is_active
      and input_score >= rule.min_score
      and (not rule.requires_success or input_success)
    order by rule.priority desc
    limit 1;

    if selected_ticket_type is not null then
      insert into public.game_rewards (game_play_id, user_id, ticket_type)
      values (input_play_id, auth.uid(), selected_ticket_type)
      on conflict (game_play_id) do nothing;

      if found then
        insert into public.wish_ticket_balances (user_id, ticket_type, quantity)
        values (auth.uid(), selected_ticket_type, 1)
        on conflict (user_id, ticket_type) do update
        set quantity = public.wish_ticket_balances.quantity + 1, updated_at = now();
      end if;
    end if;
  end if;

  return query
  select
    target_play.id,
    reward.ticket_type,
    coalesce(reward.quantity, 0),
    coalesce((select balance.quantity from public.wish_ticket_balances balance where balance.user_id = auth.uid() and balance.ticket_type = 'normal'), 0),
    coalesce((select balance.quantity from public.wish_ticket_balances balance where balance.user_id = auth.uid() and balance.ticket_type = 'premium'), 0)
  from (select 1) seed
  left join public.game_rewards reward on reward.game_play_id = target_play.id;
end;
$$;

revoke all on function public.start_game(text) from public;
revoke all on function public.finish_game(uuid, integer, boolean) from public;
grant execute on function public.start_game(text) to authenticated;
grant execute on function public.finish_game(uuid, integer, boolean) to authenticated;
grant select on public.game_definitions, public.game_reward_rules, public.game_plays, public.game_rewards to authenticated;
